### ISSUE TITLE
Srediti CSS

### ISSUE THREAD

**Issue by kalinicm** [Limunce/FB#19]
Ne znam da li i tebi izlazi isto, ali ovo nije ni izbliza vizuelno ono sto je trazeno.
Pogledaj skrinove ispod i javi...

CSS je kljuc frontenda, a react/js su tu da to omoguce, ali je CSS taj koji gura pricu. CSSom mora da se vlada i da se moze napraviti sta je potrebno.

Nisam gledao kod jer dok ne valjda proizvod nema sta da se analizira kod, a verujem da je ok taj deo. Samo vizuelno ovo nije, meni deluje kao da nema CSSa nimalo.

Ima element u htmlu sa className="stories-sidebar" ali nigde nema CSSa.

Kloniraj ovaj repo u neki drugi direktorijum pa vidi. Moguce je da ti neki deo CSSa nije ukljucen u commit, definitivno kao da nesto fali.

<img width="1313" alt="screenshot 2019-01-12 at 16 50 05" src="https://user-images.githubusercontent.com/172022/51075324-37dc6780-168a-11e9-94f4-4791b0938bc8.png">
<img width="733" alt="screenshot 2019-01-05 at 21 22 22" src="https://user-images.githubusercontent.com/172022/51075326-390d9480-168a-11e9-93e8-9225f928d6c5.png">

**Comment by Limunce** [comment]
Ne, ovo definitivno nije nista kako treba. Tacno sam zezno nesto kod commit-ovanja.
Pogledam i javim

**Comment by Limunce** [comment]
@kalinicm  Zato sto imam cetiri brancha gde sam menjao JS tj dodavao jos className-ova i onda ovi css branch-ovi ne vide class jer ga nema. 
Sad cu da mergujem ova cetiri JS brancha, pa cu onda da vidim.
Trebao sam lepo jedan po jedan branch pa kad odobris da idem dalje, nego ja odmah napravio za svaku komponentu..

**Comment by Limunce** [comment]
@kalinicm Ili da zatvorim sve ove PR-ove pa iz pocetka jedan po jedan?
Sta ti mislis?

**Comment by Limunce** [comment]
@kalinicm 
Prebacio sam ceo kod u novi direktorijum, ovo vec lici na kod koji sam uradio.

http://prntscr.com/m6bkmk

**Comment by kalinicm** [comment]
:) bas gledam sta si tacno uradio da ti objasnim kako da pridjes pravilno
da se ne zapetljas..  Skrinsot izgleda super..

*Kako je trebalo da se odradi:*
1. da se CSS strukture napravi da stoji tacno gde treba
2. da se 1 po 1 komponenta menja u strukturi iz tacke 1. tako da se jasno
vidi kada prebacis branch koja je komponenta izmenjena, a struktura drzi
sve na istom mestu
3. nikako ne treba praviti vise PRova za istu komponentu koju trenutno
menjamo, nastane haos

*Drugim recima:*
Zamisli sahovsku tablu, 8x8 polja ako se ne varam. TI prvo moras da
napravis DIVove koji drze tu strukturu tacno kako treba bez mrdanja, potom
uzmes samo jedno polje u toj 8x8 matrici i samo njega radis u tom 1 PRu. Ja
kako swichujem branchove mi se menja samo jedno polje i onda to ima smisla.
Ako ti skontas da u toku rada na menjanju jednog polja moras da cacnes
strukturu 8x8 matrice, onda ces sve ostalo poremetiti donekle i onda svi
ostali PRovi su u problemu. Dakle, pre nego sto krenes da napadas vise
polja iz 8x8 matrice, moras da budes siguran da neces dirati samu 8x8
matricu. Mislim da je ovde greska bila samo sto nisi tu matricu (strukturu)
utegao kako treba pre nego sto si krenuo da cackas polja i to sto si isto
polje stavio u vise PRova.

Ovo je dobro iskustvo da razumes da ne sme da se dira parent deo aplikacije
(matrica 8x8 u ovom primeru) dok se radi paralelno na vise polja. Ako moras
da dirnes u matricu 8x8, onda bolje se vrati na master i napravi izmenu i
merguj u master i onda rebaseuj sve svoje branchove na taj novi master gde
je matrica 8x8 sredjena, pa onda nastavi sa PRom za svako polje ponaosob. I
nikako vise PRova za isto "polje u matrici".

Iz mastera napravi novi branch i prebaci sve u taj jedan branch i posalji,
kada taj branch mergujemo u master, sve ovo ostalo ces obrisati kao visak,
ali ne pre nego sto novi branch sa svim izmenama ne mergujemo u master...

Bice tu jos poliranja, ali si odradio po skrinsotu dosta i zaista deluje
production.

PS. Ja sam sada tu, nece biti procepa vremenskih, morao sam da zavrsim
bitne stvari.
PPS. Kad budem zadovoljan sa ovim sto sad radis, dobices jos par detalja
sitnih da savladas, tipa prebacivanje hooks u Class komponentu i jos neki
sitan detalj i to je to, pisemo CV.
PPPS. Obavezno mi sve ovo povezi na bazu podataka, ne racunam da je reseno
dok nije permanentno snimljeno u bazu i povezano sa aplikacijom.

Mit freundlichen Grüßen / Best regards,
Milan Kalinic
