### ISSUE TITLE
A href tag

### ISSUE THREAD

**Issue by Limunce** [Limunce/FB#21]
Imao sam problem sa a href tagom, jer nisam stavljao putanju da mi ne bi linkovao, a kad ostavim # onda mi prijavljuje gresku u konzoli.

Koliko sam procitao jedino resenje je da sve a href zamenim sa button, pa cu tako i uraditi ali mislim da cu onda imati neke probleme sto se tice CSS-a, jer dugme ima vece dimenzije ali resicu.

Ovde nema SS jer kad otvoris konzolu videces gomilu upozorenja.

Nije mi ni na pamet palo da cu da imam ovakav problem, koristio bih odmah button-e.

**Comment by kalinicm** [comment]
ovo sam ti ubacio u komentare, videces.. moras da stavis preventDefault() da taj # ne bi bio izvrsen..

```
<a href="#" onClick={e=> { e.preventDefault() .... }} ....>...</a>
```

**Comment by Limunce** [comment]
@kalinicm 
Ovo sam uradio ali i dalje mi izbacuje greske u konzoli
