### ISSUE TITLE
Dodavanje post-ova

### ISSUE THREAD

**Issue by Limunce** [Limunce/FB#22]
Sto se tice dodavanja post-ova, posto kod njih je to malo drugacije iskace im neki prozor pa onda ti tu nudi jos neke opcije koje nisam siguran da bih znao da napravim, napravio sam dve opcije:
1.ima dugme share 
ili
2.nakon zavrsetka kucanja pritisne se enter da se posalje post

Moj:
http://prntscr.com/m7wluj

njihov:
http://prntscr.com/m80shu
Ovo mi i nije neki issue jer radi, ali opet nije isto kao kod njih

**Comment by kalinicm** [comment]
sasvim dovoljno, ne treba dalje...

**Comment by kalinicm** [comment]
smatraj da je ovo reseno...
