### ISSUE TITLE
left sidebar

### ISSUE THREAD

**Issue by Limunce** [Limunce/FB#23]
Primetio sam da kada na FB kliknes recimo na News Feed tab sa strane, on ostane oznacen tj promeni se background color, ali nisam uspeo da namestim. Sve neki primeri sa JQuiery

http://prntscr.com/m7wml2

**Comment by kalinicm** [comment]
ovo ne vidim u poslednjoj verziji appa..

**Comment by Limunce** [comment]
Nisam se dobro izrazio, ovo se desava na pravom FB-u, ja kod mene nisam uspeo to da namestim.
Slika je sa pravog FB-a.
