### ISSUE TITLE
Sticky nav bar and sidebars

### ISSUE THREAD

**Issue by Limunce** [Limunce/FB#24]
Primetio sam da su kod njih Navigation bar i sidebar-ovi sticky.
(Potrebno je dodati vise postova da bi se efekat video)

Probao sam to da napravim i delicmino sam uspeo:

- Za navigation bar i left sidebar RADI ali samo do nekog scroll-a tj. kada se doda vise post-ova u nekom trenutku nestaju i navigation bar i left sidebar.

- Ne znam zasto dodavanje postition:sticky NE RADI za right sidebar kao sto radi za left, ali pretpostavljam zbog pozicioniranja u grid-u

**Comment by kalinicm** [comment]
da, grid ti je malo kompleksniji pa zbog toga se nesto ukrstilo kako ne treba...

**Comment by kalinicm** [comment]
radi na drugoj strani, nemoj gubiti vreme za peglanje ovoga.. sve ok
