### ISSUE TITLE
Polje za dodavanje komentara

### ISSUE THREAD

**Issue by Limunce** [Limunce/FB#25]
Sto se tice polja za dodavanje komentara, nisam uspeo da ga ogranicim da mi tekst ne ide iza one 4 slicice.

http://prntscr.com/m7wqgs

Ali imam neku ideju kako bih to mozda resio.

Probacu i javljam.

inace koristim ovaj npm modul da textarea u ovom slucaju:
https://www.npmjs.com/package/react-textarea-autosize

**Comment by Limunce** [comment]
Nisam uspeo onako kako sam mislio jer na textarea ne moze da se stavi display grid.

Hteo sam da napravim dve kolone unutar textarea i problem resen.

Probacu da nadjem da li moze da se recimo setuje maxlength i kad dodje do max da se prebaci u novi red.

**Comment by kalinicm** [comment]
jednostavno je.
napravis jedan div koji ima tu sivu pozadinu i border
u taj div ubacis 2 diva horizontalno
u levi div stavis textarea bez stajlinga a u desni div stavis slicice i sve radi..
sa divovima pravis strukturu, ni sa cim drugim..
